name: Pre-Release

on:
  pull_request:
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: pre release

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Retrieve Project Metadata
        uses: radcortez/project-metadata-action@95ed3b828c4563fb1c1c9f4c319eceb9ce7de1b3
        id: metadata
        with:
          metadata-file-path: '.github/project.yml'

      - name: Review Milestone
        uses: radcortez/milestone-review-action@1126e9e9db5e39f8e3b6795d2718d73800ac89c5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          milestone-title: ${{steps.metadata.outputs.current-version}}
